source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.6'
# Use pg as the database for Active Record
gem 'pg'

gem 'rails_12factor', group: :production
gem 'jquery-rails', "~> 2.3.0"
gem 'turbolinks'
gem 'jwt'
gem 'twitter_oauth'
gem 'httpclient'
gem 'responders', '~> 2.0'
gem 'active_model_serializers', '~> 0.8.2'
gem 'bcrypt', '~> 3.1.7'
gem 'sinatra'
gem 'paperclip', "5.0.0"
gem 'uglifier'
gem 'rest_client'
gem "mini_magick"
gem 'aws-sdk'
gem 'httparty'
gem 'devise'
gem 'rack-cors', :require => 'rack/cors'
gem 'thin', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'

  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

